### ISSUE TITLE
Lib.rs Line 628 error with Result type

### ISSUE THREAD

**Issue by GuruKathryn** [goede-dapps/Geode-Social#1]
In the lib.rs file, line 628 has a problem when we use the non-reentrant modifier...

```
        #[ink(message)]
        #[openbrush::modifiers(non_reentrant)]
        pub fn elevate_paid_message(&mut self, owner: AccountId, this_message_id: Hash
        ) -> Result<(), ReentrancyGuardError> {
```

When we compile we get the following errors...

- expected `Result<(), ...>`, found `Result<(), Error>`
- expected `Result<(), ReentrancyGuardError>` because of return type
- expected enum `Result<_, ReentrancyGuardError>` found enum `Result<_, geode_social::Error>`

**Comment by ganesh1233456** [comment]
ya I fixed it, basically what you are doing there is, you set return type `ReentrancyGuardError ` but on line 639 you try to return error from `Error`, which might not efficient.

<img width="1427" alt="Screenshot 2023-03-22 at 08 27 15" src="https://user-images.githubusercontent.com/42571338/226788242-afedb073-0fb1-4ccf-887b-9a695b81cbe7.png">

**Comment by GuruKathryn** [comment]
Perfect! It's funny how I can see my way through the hard problems but somehow miss the easy ones. LOL.
