### ISSUE TITLE
contract deployment error in goede-chain

### ISSUE THREAD

**Issue by ganesh1233456** [goede-dapps/Geode-Social#2]
deploying contract locally it works but when I try to deploy same contract in `Goede-chain` it error message `Storage Deposit Limit` and the thing is I have goede token in account.

<img width="1427" alt="Screenshot 2023-03-22 at 08 46 40" src="https://user-images.githubusercontent.com/42571338/226791194-8387068f-2175-4d32-b4cd-87a70b5b08a8.png">

**Comment by GuruKathryn** [comment]
Right! This is a problem in the UI. We saw the same issue and found that version of the UI that is operating right now is using an older version of the Weights calculations to determine gas and is thus calculating the wrong gas and thinking you are out of gas. We are integrating WeightsV2 for the next update on the UI and it solves the problem. We should have that up in the next week or two.

**Comment by ganesh1233456** [comment]
> Right! This is a problem in the UI. We saw the same issue and found that version of the UI that is operating right now is using an older version of the Weights calculations to determine gas and is thus calculating the wrong gas and thinking you are out of gas. We are integrating WeightsV2 for the next update on the UI and it solves the problem. We should have that up in the next week or two.

but the thing is when I build new contract and upload then it works

**Comment by GuruKathryn** [comment]
Hmmm... for us it caused out-of-gas problems on every contract version. I know that with weightsV2 integrated, it works the first time and every time.

**Comment by GuruKathryn** [comment]
issue fixed with previous UI upgrade.
